### ISSUE TITLE
.proto

### ISSUE THREAD

**Issue by Turkisec** [nosoxon/snapchat-protobuf-decoder#1]
how did you get or gen the [content.proto](https://github.com/nosoxon/snapchat-protobuf-decoder/blob/master/content.proto)

**Comment by nosoxon** [comment]
I just wrote it manually based on [this](https://github.com/nosoxon/snapchat-protobuf-decoder/blob/master/research/protobuf_config.py), which I created with the help of [protobuf-inspector](https://github.com/mildsunrise/protobuf-inspector). You could probably write something to convert `protobuf_config.py` to the protobuf description.
